-   id: flake8
    name: flake8
    description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
    entry: flake8
    language: python
    types_or: [python, pyi]
    require_serial: true
    minimum_pre_commit_version: 2.9.2
